upstream/config/routes.rb
Rails.application.routes.draw do

  get '/download', :to => 'pages#download'  
  get '/api_doc', :to => 'pages#api_doc'  

  resources :combinations do
    collection do
      get 'interogate'
      get 'unknown'
      get 'unrated'
    end
    member do
      get 'calculate'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :combinations do
        collection do 
          get 'interogate'
        end
      end
      get 'download', :to => 'static#download'
    end
  end

  resources :mac_vendors

  resources :dhcp_vendors

  resources :discoverers

  resources :rules do
    resources :conditions
  end

  resources :dhcp_fingerprints

  resources :devices do 
    get 'community', on: :new, :to => 'devices#community_new'
    post 'community', on: :new, :to => 'devices#community_create'

    collection do
      get 'not_approved'
    end
  
    member do 
      get 'approve'
    end
  end

  resources :users do
    member do
      post 'promote_admin'
      post 'demote_admin'
      get 'generate_key'
    end
  end

  get '/login', :to => 'users#login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'

  root 'combinations#index' 

end

upstream/app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :github_uid, :name
  validates_uniqueness_of :github_uid, :display_name

  has_many :combinations, :foreign_key => "submitter_id"
  has_many :devices, :foreign_key => "submitter_id"

  scope :admins, -> {where(:level => 1)}
  scope :community, -> {where(:level => 0)}

  after_create :generate_key

  def generate_key
    require 'digest/sha1'
    self.key = Digest::SHA1.hexdigest "API-#{Time.now}-#{github_uid}"
    self.save
  end

  def add_request
    if self.requests.nil?
      self.requests = 1
      save!
    else
      self.requests += 1
      save!
    end
  end

  def self.from_omniauth(auth)
    user = self.where(:github_uid => auth.uid).first
    if user 
      user.update!(:github_uid => auth.uid, :name => auth.info.nickname, :display_name => auth.info.name)
    else
      create(:github_uid => auth.uid, :name => auth.info.nickname, :display_name => auth.info.name)
    end
    return self.where(:github_uid => auth.uid).first 
  end

  def promote_admin
    update(:level => 1)
  end

  def demote_admin
    if User.admins.size > 1
      update(:level => 0)
    else
      return false 
    end
  end

  def admin?
    level >= 1
  end

end

upstream/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :promote_admin, :demote_admin, :generate_key]
  
  skip_before_filter :ensure_admin

  before_filter :admin_or_current_user
  skip_before_filter :admin_or_current_user, :only => [:login]

  def admin_or_current_user
    unless @current_user == @user || @current_user.admin? 
      flash[:error] = "You need to login to access this user"
      redirect_to root_path
    end
  end

  def show
  end

  def login
    unless session[:previous_page]
      session[:previous_page] = request.referer 
    end
    redirect_to '/auth/github'
  end

  def promote_admin
    if @user.promote_admin
      flash[:success] = "User promoted to admin"
    else
      flash[:error] = "Couldn't promote the user to an admin"
    end
    redirect_to users_path
  end

  def demote_admin
    if @user.demote_admin
      flash[:success] = "User demoted"
    else
      flash[:error] = "Couldn't demote the user" 
    end
    redirect_to users_path
  end

  def generate_key
    @user.generate_key
    if @user.save
      flash[:success] = "Generated key #{@user.key}"
    else
      flash[:error] = "Can't generate key"
    end
    redirect_to :back
  end

  def index
    @users = User.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end


end

upstream/app/views/users/_users.html.erb
<table>
<tr>
  <th></th>
  <th>Github user ID</th>
  <th>Username</th>
  <th>Display name</th>
  <th></th>
</tr>
<% users.each do |user| %>
  <tr>
    <td><%= link_to '', user_path(user), :class => 'btn-show' %></td>
    <td><%= user.github_uid %></td>
    <td><%= user.name %></td>
    <td><%= user.display_name %></td>
    <% unless user.admin? %>
      <td><%= link_to 'Promote admin', promote_admin_user_path(user), method: :post, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" if current_user_admin? %></td>
    <% else%>
      <td><%= link_to 'Demote admin', demote_admin_user_path(user), method: :post, data: { confirm: 'Are you sure?' }, :class => "btn btn-warning" if current_user_admin? %></td>
    <% end %>
  </tr>
<% end %>

</table>

upstream/app/views/users/index.html.erb
<h3>Admin users</h3>
<%= render :partial => 'users', :locals => {:users => User.admins} %>

<h3>Normal users</h3>
<%= render :partial => 'users', :locals => {:users => User.community} %>

upstream/app/views/users/show.html.erb
<p>
  <strong>Github user ID:</strong>
  <%= @user.github_uid %>
</p>
<p>
  <strong>Username:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Display name:</strong>
  <%= @user.display_name %>
</p>
<p>
  <strong>API key:</strong>
  <%= @user.key %>
</p>
<p>
  <strong>Number of requests:</strong>
  <%= @user.requests %>
</p>

<%= link_to "Generate key", generate_key_user_path(@user) %>
<%= link_to "Manage other users", users_path if current_user_admin? %>