upstream/config/routes.rb
Rails.application.routes.draw do

  get '/download', :to => 'pages#download'  
  get '/api_doc', :to => 'pages#api_doc'  

  resources :combinations do
    collection do
      get 'interogate'
      get 'unknown'
      get 'unrated'
    end
    member do
      get 'calculate'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :combinations do
        collection do 
          get 'interogate'
        end
      end
      get 'download', :to => 'static#download'
    end
  end

  resources :mac_vendors

  resources :dhcp_vendors

  resources :discoverers

  resources :rules do
    resources :conditions
  end

  resources :dhcp_fingerprints

  resources :devices do 
    get 'community', on: :new, :to => 'devices#community_new'
    post 'community', on: :new, :to => 'devices#community_create'

    collection do
      get 'not_approved'
    end
  
    member do 
      get 'approve'
    end
  end

  resources :users do
    member do
      post 'promote_admin'
      post 'demote_admin'
      get 'generate_key'
    end
  end

  get '/login', :to => 'users#login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'

  root 'combinations#index' 

end

upstream/app/models/discoverer.rb
class Discoverer < ActiveRecord::Base
  has_many :device_rules, :class_name => 'Rule', :foreign_key => 'device_discoverer_id'
  has_many :version_rules, :class_name => 'Rule', :foreign_key => 'version_discoverer_id'
  belongs_to :device

  validates_presence_of :device_id
  validates_presence_of :description
  validates :priority, :numericality => {:only_integer => true}

  def version_finder
    if self.version.nil?
      return "''"
    elsif self.version.match(/^PREG_CAPTURE/) || self.version.match(/^REPLACE/)
      return self.version
    else
      return "'#{self.version}'"
    end
  end
end

upstream/app/controllers/discoverers_controller.rb
class DiscoverersController < ApplicationController
  before_action :set_discoverer, only: [:show, :edit, :update, :destroy]
  before_action :set_index_help, only: [:index]
  before_action :set_show_help, only: [:show]

  # GET /discoverers
  # GET /discoverers.json
  def index
    @discoverers = Discoverer.all
  end

  # GET /discoverers/1
  # GET /discoverers/1.json
  def show
  end

  # GET /discoverers/new
  def new
    @discoverer = Discoverer.new
    if device_id_param
     @discoverer.device = Device.find(device_id_param) 
    end 
  end

  # GET /discoverers/1/edit
  def edit
  end

  # POST /discoverers
  # POST /discoverers.json
  def create
    @discoverer = Discoverer.new(discoverer_params)

    respond_to do |format|
      if @discoverer.save
        format.html { redirect_to @discoverer, notice: 'Discoverer was successfully created.' }
        format.json { render :show, status: :created, location: @discoverer }
      else
        format.html { render :new }
        format.json { render json: @discoverer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discoverers/1
  # PATCH/PUT /discoverers/1.json
  def update
    respond_to do |format|
      if @discoverer.update(discoverer_params)
        format.html { redirect_to @discoverer, notice: 'Discoverer was successfully updated.' }
        format.json { render :show, status: :ok, location: @discoverer }
      else
        format.html { render :edit }
        format.json { render json: @discoverer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discoverers/1
  # DELETE /discoverers/1.json
  def destroy
    @discoverer.destroy
    respond_to do |format|
      format.html { redirect_to discoverers_url, notice: 'Discoverer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discoverer
      @discoverer = Discoverer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discoverer_params
      params.require(:discoverer).permit(:description, :priority, :device_id, :version, :device_rule_ids => [], :version_rule_ids => [])
    end

    def device_id_param
      params[:device_id]
    end

    def set_index_help
      @help = %Q(The discoverers listed here are the core of Fingerbank.
                 These will parse the data that is sent to Fingerbank in order to categorize the combination of DHCP fingerprint, DHCP vendor, User Agent and MAC vendor.
      )
    end

    def set_show_help
      @help = %Q(On this page you can see the attributes that define the discoverer.
                 The priority is the amount that will be added to a device score if one of the device rules matches the combination.
                 The version is either an SQL extractor for the version or simply the version of the device when matching any version rule.
                 The device is the associated device to that discoverer. When matching it, it means the combination belongs to this device.
                 The devices rules are what matches the combination attributes and if they match then this discoverer is valid for that combination.
                 The version rules are what attributes a combination should match in order to be attributed the specified version in the discoverer.
      )
    end
end

upstream/app/helpers/discoverers_helper.rb
module DiscoverersHelper
end

upstream/app/views/discoverers/_form.html.erb
<%= form_for(@discoverer) do |f| %>
  <% if @discoverer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discoverer.errors.count, "error") %> prohibited this discoverer from being saved:</h2>

      <ul>
      <% @discoverer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.text_field :priority %>
  </div>

  <div class="field">
    <%= f.label "Associated device" %><br/>
    <%= f.hidden_field :device_id %>
    <%= render :partial => 'devices/devices_selection', :locals => {:set => '#discoverer_device_id', :selected => @discoverer.device} %>
  </div>

  <div class="field">
    <%= f.label :version %>
    <%= f.text_field :version %>
  </div>

  <% if @discoverer.persisted? %>
    <a href="<%= new_rule_path %>?version_discoverer_id=<%= @discoverer.id %>">New version rule</a>
    <a href="<%= new_rule_path %>?device_discoverer_id=<%= @discoverer.id %>">New Device rule</a>
  <% end %>

  <input name="discoverer[device_rule_ids][]" value="" type="hidden">
  <% @discoverer.device_rules.each do |rule| %>
    <div>
      <button onclick="javascript:$(this).parent().remove()">-</button>
      <a href="<%= edit_rule_path(rule) %>">edit</a>
      <input name="discoverer[device_rule_ids][]" value="<%=rule.id%>" type="hidden">
      <span><%= rule.value %></span>
    </div>
  <% end %>

  <input name="discoverer[version_rule_ids][]" value="" type="hidden">
  <% @discoverer.version_rules.each do |rule| %>
    <div>
      <button onclick="javascript:$(this).parent().remove()">-</button>
      <a href="<%= edit_rule_path(rule) %>">edit</a>
      <input name="discoverer[version_rule_ids][]" value="<%=rule.id%>" type="hidden">
      <span><%= rule.value %></span>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

upstream/app/views/discoverers/edit.html.erb
<h1>Editing discoverer</h1>

<%= render 'form' %>

<%= link_to 'Show', @discoverer %> |
<%= link_to 'Back to Devices', device_path(@discoverer.device) %>

upstream/app/views/discoverers/index.html.erb
<table>
  <thead>
    <tr>
      <th></th>
      <th>Description</th>
      <th>For Device</th>
    </tr>
  </thead>

  <tbody>
    <% @discoverers.each do |discoverer| %>
      <tr>
        <td>
          <%= link_to '', discoverer, :class => "btn-show" %>
          <%= link_to '', edit_discoverer_path(discoverer), :class => "btn-edit" if current_user_admin? %>
          <%= link_to '', discoverer, method: :delete, :data => { confirm: 'Are you sure?' }, :class => "btn-delete" if current_user_admin? %>
        </td>
        <td><%= discoverer.description %></td>
        <td><%= discoverer.device.name unless discoverer.device.nil? %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discoverer', new_discoverer_path %>

upstream/app/views/discoverers/new.html.erb
<h1>New discoverer</h1>

<%= render 'form' %>

<%= link_to 'Back to Devices list', devices_path %>

upstream/app/views/discoverers/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Description</h3>
<%= @discoverer.description %>

<h3>Priority</h3>
<%= @discoverer.priority %>

<h3>Device</h3>
<%= @discoverer.device.full_path %>

<h3>Version</h3>
<%= @discoverer.version %>

<h3>Device rules</h3>
<table>
<th></th>
<th></th>
<th></th>
<th>Rule id</th>
<th>Computed rule</th>
<% @discoverer.device_rules.each do |rule| %>
  <tr>
  <td><%= link_to '', rule, :class => "btn-show" %></td>
  <td><%= link_to '', edit_rule_path(rule), :class => "btn-edit" if current_user_admin? %></td>
  <td><%= link_to '', rule, method: :delete, :data => { confirm: 'Are you sure?' }, :class => "btn-delete" if current_user_admin? %></td>
  <td><%= rule.id %></td>
  <td><%= rule.computed %></td>
  </tr>
<% end %>
</table>

<h3>Version rules</h3>
<table>
<th></th>
<th></th>
<th></th>
<th>Rule id</th>
<th>Computed rule</th>
<% @discoverer.version_rules.each do |rule| %>
  <tr>
  <td><%= link_to '', rule, :class => "btn-show" %></td>
  <td><%= link_to '', edit_rule_path(rule), :class => "btn-edit" if current_user_admin?%></td>
  <td><%= link_to '', rule, method: :delete, :data => { confirm: 'Are you sure?' }, :class => "btn-delete" if current_user_admin? %></td>
  <td><%= rule.id %></td>
  <td><%= rule.computed %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_discoverer_path(@discoverer) if current_user_admin? %> 
<%= link_to 'Back to Device', device_path(@discoverer.device) %>