upstream/config/routes.rb
Rails.application.routes.draw do

  get '/download', :to => 'pages#download'  
  get '/api_doc', :to => 'pages#api_doc'  

  resources :combinations do
    collection do
      get 'interogate'
      get 'unknown'
      get 'unrated'
    end
    member do
      get 'calculate'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :combinations do
        collection do 
          get 'interogate'
        end
      end
      get 'download', :to => 'static#download'
    end
  end

  resources :mac_vendors

  resources :dhcp_vendors

  resources :discoverers

  resources :rules do
    resources :conditions
  end

  resources :dhcp_fingerprints

  resources :devices do 
    get 'community', on: :new, :to => 'devices#community_new'
    post 'community', on: :new, :to => 'devices#community_create'

    collection do
      get 'not_approved'
    end
  
    member do 
      get 'approve'
    end
  end

  resources :users do
    member do
      post 'promote_admin'
      post 'demote_admin'
      get 'generate_key'
    end
  end

  get '/login', :to => 'users#login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'

  root 'combinations#index' 

end

upstream/app/models/rule.rb
class Rule < ActiveRecord::Base
  has_many :conditions
  belongs_to :device_discoverer, :class_name => 'Discoverer', :foreign_key => 'device_discoverer_id'
  belongs_to :version_discoverer, :class_name => 'Discoverer', :foreign_key => 'version_discoverer_id'

  validates_presence_of :value
  validate :passes_syntax

  accepts_nested_attributes_for :conditions, :allow_destroy => true

  def passes_syntax
    true
  end

  def computed 
    tmp_value = value
    conditions.each do |condition|
      tmp_value.gsub!(Regexp.new(Regexp.escape(condition.key)), condition.value)
    end
    tmp_value
  end
end

upstream/app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]
  before_action :set_show_help, only: [:show]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
    if device_discoverer_id_param 
      @rule.device_discoverer = Discoverer.find(device_discoverer_id_param)
    elsif version_discoverer_id_param
      @rule.version_discoverer = Discoverer.find(version_discoverer_id_param)
    end
    @condition = Condition.new
  end

  # GET /rules/1/edit
  def edit
    @condition = Condition.new
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)
    create_result = @rule.save

    condition_result = true
    unless condition_params.values.all? {|x| x.empty?}
      @condition = Condition.create(condition_params)
      @rule.conditions << @condition 
      condition_result = @rule.save
    else
      @condition = Condition.new
    end

    respond_to do |format|
      if create_result && condition_result
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
    unless condition_params.values.all? {|x| x.empty?}
      @rule.conditions << Condition.create(condition_params)
      @rule.save
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    update_result = @rule.update(rule_params)

    condition_result = true
    unless condition_params.values.all? {|x| x.empty?}
      @condition = Condition.create(condition_params)
      @rule.conditions << @condition 
      condition_result = @rule.save
    else
      @condition = Condition.new
    end

    respond_to do |format|
      if update_result && condition_result 
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:value, :device_discoverer_id, :version_discoverer_id, :condition_ids => [])
    end

    def condition_params
      params.require(:condition).permit(:key, :value)
    end

    # permit an version_discoverer_id to be passed for smoother creation
    def version_discoverer_id_param
      params[:version_discoverer_id]
    end

    # permit an version_discoverer_id to be passed for smoother creation
    def device_discoverer_id_param
      params[:device_discoverer_id]
    end

    def set_show_help
      @help = %Q(This page shows what the rule is matching.
                 The rules use the SQL syntax and are injected into a query to perform the match.
                 The tables available for the match are : dhcp_fingerprints, dhcp_vendors, user_agents, mac_vendors
                 For more information on the fields, refer to the SQL schema.
                 The value is the raw stored query that may contain additionnal variables that are conditions.
                 The device/version discoverer is it's associated discoverer.
                 The computed value is the end SQL that will be injected in the query.
      )
    end
end

upstream/app/helpers/rules_helper.rb
module RulesHelper
end

upstream/app/views/rules/_back.html.erb
<% if @rule.device_discoverer %>
  <%= link_to 'Back to Devices discoverer', discoverer_path(@rule.device_discoverer) %>
<% end %>
<% if @rule.version_discoverer %>
  <%= link_to 'Back to version discoverer', discoverer_path(@rule.version_discoverer) %>
<% end %>
<% unless @rule.device_discoverer || @rule.version_discoverer %>
  <%= link_to 'Back to rules index', rules_path %>
<% end %>

upstream/app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :device_discoverer %>
    <%= f.collection_select(:device_discoverer_id, Discoverer.all, :id, :description, :include_blank => true) %>
  </div> 

  <div class="field">
    <%= f.label :version_discoverer %>
    <%= f.collection_select(:version_discoverer_id, Discoverer.all, :id, :description, :include_blank => true) %>
  </div>

  <input name="rule[condition_ids][]" value="" type="hidden">
  <% @rule.conditions.each do |condition| %>
    <div>
      <button onclick="javascript:$(this).parent().remove()">-</button>
      <a href="<%= edit_rule_condition_path(@rule, condition) %>">edit</a>
      <input name="rule[condition_ids][]" value="<%=condition.id%>" type="hidden">
      <span><%= condition.key %> : <%= condition.value %></span>
    </div>
  <% end %>

  <div>
    <h4>New condition</h4>
    <%= fields_for @condition do |c| %>
      <div class="field"> 
        <%= c.label :key %>
        <%= c.text_field :key %>
      </div>
      <div class="field"> 
        <%= c.label :value %>
        <%= c.text_field :value %>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

upstream/app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

upstream/app/views/rules/index.html.erb
<h1>Listing rules</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Device discoverer</th>
      <th>Version discoverer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%= rule.value %></td>
        <td><%= rule.device_discoverer_id %></td>
        <td><%= rule.version_discoverer_id %></td>
        <td><%= link_to 'Show', rule %></td>
        <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
        <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %>

upstream/app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= render 'back' %>

upstream/app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @rule.value %>
</p>

<% if @rule.device_discoverer %>
  <p>
    <strong>Device discoverer:</strong>
    <%= @rule.device_discoverer.description %>
  </p>
<% end %>

<% if @rule.version_discoverer %>
  <p>
    <strong>Version discoverer:</strong>
    <%= @rule.version_discoverer.description %>
  </p>
<% end %>

<p>
  <strong>Computed:</strong>
  <%= @rule.computed %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= render 'back' %>