upstream/config/routes.rb
Rails.application.routes.draw do

  get '/download', :to => 'pages#download'  
  get '/api_doc', :to => 'pages#api_doc'  

  resources :combinations do
    collection do
      get 'interogate'
      get 'unknown'
      get 'unrated'
    end
    member do
      get 'calculate'
    end
  end
  namespace :api do
    namespace :v1 do
      resources :combinations do
        collection do 
          get 'interogate'
        end
      end
      get 'download', :to => 'static#download'
    end
  end

  resources :mac_vendors

  resources :dhcp_vendors

  resources :discoverers

  resources :rules do
    resources :conditions
  end

  resources :dhcp_fingerprints

  resources :devices do 
    get 'community', on: :new, :to => 'devices#community_new'
    post 'community', on: :new, :to => 'devices#community_create'

    collection do
      get 'not_approved'
    end
  
    member do 
      get 'approve'
    end
  end

  resources :users do
    member do
      post 'promote_admin'
      post 'demote_admin'
      get 'generate_key'
    end
  end

  get '/login', :to => 'users#login'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'

  root 'combinations#index' 

end

upstream/app/models/device.rb
class Device < ActiveRecord::Base
  #self.table_name = "device"

  has_many :device, :foreign_key => :parent_id
  belongs_to :parent, :class_name => "Device"
  validate :parent_is_not_child
  validates_uniqueness_of :name

  has_many :discoverers
  has_many :combinations

  belongs_to :submitter, :class_name => "User"

  scope :top_level, -> {where('parent_id IS NULL')}
  scope :approved, -> {where(:approved => true)}
  scope :not_approved, -> {where(:approved => false)}

  before_destroy :set_combinations

  def set_combinations
    combinations.each do | combination |
      combination.device = nil
      combination.save
    end
  end

  def tree_discoverers
    discoverers = []
    [parents, self].flatten.each do |device|
      discoverers.push device.discoverers
    end
    discoverers.flatten
  end

  def level
    if parent
      return parent.level+1
    else
      return 1
    end
  end

  def top_level_parent
    tmp_parent = parent
    unless tmp_parent.nil?
      tmp_parent = parent.top_level_parent
      tmp_parent
    else
      self
    end
  end

  def parent_is_not_child
    if childs.flatten.include? self
      errors.add(:parent_id, "cannot be a child")
    end
  end

  def childs
    child_chain = []
    chain = self.device
    chain.each do |child|
      child_chain.push child._childs_recur
    end
    child_chain
  end

  def _childs_recur 
    child_chain = [self]
    chain = self.device
    chain.each do |child|
      child_chain.push child._childs_recur
    end
    child_chain
  end

  def self_and_childs
    child_chain = [self]
    child_chain.push childs
    child_chain
  end

  def not_self_and_childs
    tmp_childs = childs.flatten
    tmp_childs.push self
    tmp_not_childs = []
    Device.all.each do |pdevicesible_child|
      unless tmp_childs.include? pdevicesible_child
        tmp_not_childs.push pdevicesible_child
      end
    end
    tmp_not_childs
  end

  def parents
    parents_found = []
    next_parent = parent
    while !next_parent.nil? do
      parents_found << next_parent
      next_parent = next_parent.parent
    end
    parents_found
  end

  def full_path
    base = name+"/"
    unless parent.nil?
      base.prepend parent.full_path
    end
    base
  end

  def is_mobile?
    unless inherit
      mobile
    end

    parent_check = self
    while parent_check && parent_check.mobile.nil?
      parent_check = parent_check.parent
    end
    if parent_check
      parent_check.mobile
    else
      return false
    end
  end
end

upstream/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy, :approve]
  before_action :set_index_help, only: [:index]
  before_action :set_show_help, only: [:show]

  skip_before_filter :ensure_admin, :only => [:community_new, :community_create]
  before_filter :ensure_community, :only => [:community_new, :community_create]

  # GET /device
  # GET /device.json
  def index
    @devices = Device.top_level
  end

  def not_approved
    @devices = Device.not_approved
  end

  def approve
    @device.approved = true
    @device.save
    expire_device_tree @device

    flash[:notice] = "Device has been approved"
    redirect_to :back
  end

  # GET /device/1
  # GET /device/1.json
  def show
    @top_level_parent = @device.top_level_parent
  end

  def community_new
    @device = Device.new
    render 'community_new', :layout => false
  end

  def community_create
    @device = Device.new(device_params)
    @device.approved = false

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Great success. Device was successfully created.' }
        format.json { render json: @device}
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end

  end

  # GET /device/new
  def new
    @device = Device.new
  end

  # GET /device/1/edit
  def edit
  end

  # POST /device
  # POST /device.json
  def create
    @device = Device.new(device_params)
    if device_params[:inherit_mobile?]
      @device.mobile = nil
    end

    respond_to do |format|
      if @device.save
        expire_device_tree @device
        format.html { redirect_to @device, notice: 'Great success. Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device/1
  # PATCH/PUT /device/1.json
  def update

    respond_to do |format|
      if @device.update(device_params)
        expire_device_tree(@device)
        format.html { redirect_to @device, notice: 'Great success. Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device/1
  # DELETE /device/1.json
  def destroy
    @device.destroy
    expire_device_tree @device
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Great success. Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def expire_device_tree(device)
    DevicesController.action_methods.each do |method|
      expire_fragment("#{method}-device-#{device.id}")
    end
    expire_fragment("device-selection-#{device.id}")
    device.parents.each do |parent|
      expire_device_tree(parent)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :mobile, :inherit, :tablet, :parent_id, :dhcp_fingerprint_ids => [])
    end

    def set_index_help
      @help = %Q(These are all the devices that are known to Fingerbank.
                 Click on the eye next to a device to have more information about it, including how it's discovered and the matching combinations in the database.
      )
    end

    def set_show_help
      @help = %Q(On this page you can see where the device is located in the device hierarchy and it's parents and neighbors.
                 The discoverers that find combinations belonging to that device are listed below.
                 Also listed below are the matching combinations in the Fingerbank database that belong to this device.
      )
    end
    

end

upstream/app/helpers/devices_helper.rb
module DevicesHelper
end

upstream/app/views/devices/_childs.html.erb
<% cache("#{action_name}-device-#{device.id}") do %>
  <ul>
  <%= render device %>
  <% device.device.order(:name).each do |child| %>
    <%= render :partial => 'devices/childs', :locals => {:device => child} %>
  <% end %>
  </ul>
<% end %>

upstream/app/views/devices/_childs_selection.html.erb
<% cache("device-selection-#{device.id}") do %>
  <ul>
  <%= render :partial => 'devices/device_selection', :locals => { :device => device } %>
  <% device.device.order(:name).each do |child| %>
    <%= render :partial => 'devices/childs_selection', :locals => {:device => child} %>
  <% end %>
  </ul>
<% end %>

upstream/app/views/devices/_community_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this o from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Parent" %><br/>
    <%= f.hidden_field :parent_id %>
    <%= render :partial => 'devices/devices_selection', :locals => {:set => '#device_parent_id', :selected => @device.parent} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<script>
  $('#new_device').submit(function(e){
    e.preventDefault()
    alert("youpi")

    $.post('<%= community_new_device_path %>.json', $('#new_device').serialize(), function(response){
      console.log(response)
      console.log(parent)
      $(parent.document.getElementById('combination_device_id')).val(response.id)
      $(parent.document.getElementById('device_display')).html(response.name)
      // for some reason bootstrap doesn't like the modal being hidden from here
      // so we hide the backdrop and the modal
      $(parent.document.getElementById('device_creation_modal')).hide()
      $(parent.document).find('.modal-backdrop').hide()

      $(parent.document.getElementById('new_device')).hide()
      $(parent.document.getElementById('device_selection_button')).hide()
    })

  })
</script>

upstream/app/views/devices/_device.html.erb
<% if device.approved || current_user_admin? %> 
  <li>
  <span>
  <%= link_to '', device, :class => "btn-show" %>
  <!---
  <%= link_to '', edit_device_path(device), :class => "btn-edit" if current_user_admin? %>
  <%= link_to '', device, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-delete" if current_user_admin? %>
  --->
  <%= device.name.unpack("C*").pack("U*") %>
  </span>
  </li>
<% end %>

upstream/app/views/devices/_device_selection.html.erb
<li>
<span>
<%= link_to device.name, 'javascript:void(0)', :class => 'device_selection', 'data-device-id' => device.id %>
</span>
</li>

upstream/app/views/devices/_devices_selection.html.erb
<!-- Button trigger modal -->
<h5 id="device_display" ><%= selected ? selected.full_path : 'Not selected' %></h5>
<button type="button" id="device_selection_button" class="btn btn-primary" >
  Select Device 
</button>


<!-- Modal -->
<div class="modal fade" id="device_selection_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body" style="overflow-y:scroll">
        <% Device.top_level.each do |device| %>
          <%= render :partial => 'devices/childs_selection', :locals => {:device => device} %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to "Unselect", 'javascript:void(0)', :class => 'device_selection btn btn-warning', 'data-device-id' => '' %>
      </div>
    </div>
  </div>
</div>

<script>
  $('#device_selection_button').on('click', function(){
    $('#device_selection_modal').modal('show')
  });
  $('#device_selection_modal').on('show.bs.modal', function () {
    $('.modal-body').css('height',$( window ).height()*0.6);
  });
  $('#device_selection_modal .device_selection').click(function(){
    $("<%= set %>").val($(this).attr('data-device-id'))
    var content = $(this).html()
    if (content == "Unselect") content = "Not selected"
    $("#device_display").html(content)
    $('#device_selection_modal').modal('hide')
  })
</script>

upstream/app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this o from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :mobile %>
    <%= f.check_box :mobile %>
  </div>

  <div class="field">
    <%= f.label :inherit %>
    <%= f.check_box :inherit %>
  </div>

  <div class="field">
    <%= f.label :tablet %>
    <%= f.check_box :tablet %>
  </div>

  <div class="field">
    <%= f.label "Parent" %><br/>
    <%= f.hidden_field :parent_id %>
    <%= render :partial => 'devices/devices_selection', :locals => {:set => '#device_parent_id', :selected => @device.parent} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

upstream/app/views/devices/community_new.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<style>
  body{
    width:100%;
  }
</style>

<%= render 'community_form' %>

upstream/app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Index', devices_path %>

upstream/app/views/devices/index.html.erb
<div>
  <%= link_to "See not approved", not_approved_devices_path, :class => "btn btn-primary" if current_user_admin? %>
</div>

<% @devices.each do |device| %>
  <%= render :partial => 'childs', :locals => {:device => device} %>
<% end %>
<%= link_to 'New Device', new_device_path %>

upstream/app/views/devices/new.html.erb
<h1>New o</h1>

<%= render 'form' %>

<%= link_to 'Index', devices_path %>

upstream/app/views/devices/not_approved.html.erb
<% @devices.each do |device| %>
  <p>
  <%= link_to '', approve_device_path(device), :class => 'btn btn-success glyphicon glyphicon-ok' %>
  <%= link_to '', device_path(device), :class => 'btn-show' %>
  <%= link_to '', edit_device_path(device), :class => 'btn-edit' %>
  <%= link_to '', device, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-delete" %>
  <%= device.full_path %>
  </p>
<% end %>

upstream/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

Name : <%= @device.name %> <br/>
Mobile : <%= @device.is_mobile? %> <br/>
Tablet : <%= @device.tablet %> <br/>
Full path : <%= @device.full_path %> <br/>

<h3>Hierarchy</h3>
<%= render :partial => 'childs', :locals => {:device => @top_level_parent } %>

<h3>
  Discoverers 
  <% if current_user_admin? %>
    <a href="<%= new_discoverer_path %>?device_id=<%= @device.id %>">New</a>
  <% end %>
</h3>
<div  style="height:300px;overflow-y:scroll">
<table>
<% @device.discoverers.each do |discoverer| %>
  <tr>
    <td><a href="<%= discoverer_path discoverer %>"><%= discoverer.description %></a></td>
  </tr>
<% end %>
</table>
</div> 

<h3>Matching combinations</h3>
<div  style="height:300px;overflow-y:scroll">
<table>
<% @device.combinations.each do |combination| %>
  <tr>
    <td><%= combination.dhcp_fingerprint.value %></td>
    <td><%= combination.user_agent.value %></td>
    <td><%= combination.dhcp_vendor.value %></td>
  </tr>
<% end %>
</table>
</div>

<%= link_to 'New', new_device_path if current_user_admin? %> 
<%= link_to 'Edit', edit_device_path(@device) if current_user_admin? %> 
<%= link_to 'Back', devices_path %>